export default {
  website: {
    root: 'min-h-screen bg-[#F4DEC2] text-slate-900 selection:bg-emerald-300/30 font-fraunces',
    navLink: 'text-slate-700 hover:text-emerald-600',
    primaryBtn: 'bg-black text-white rounded-lg shadow-xl hover:shadow-2xl hover:scale-105 transform transition duration-200 ease-in-out',
    secondaryBtn: 'bg-white border border-gray-300 text-black rounded-lg hover:border-black  ',
    cardBg: 'bg-white/70 ring-slate-200/50',
    text: 'text-slate-600',
    statText: 'text-sm text-slate-500',
    icon: 'text-slate-700 hover:text-emerald-600',
    headerBg: 'bg-white/70 backdrop-blur-lg shadow-md',
    navbarBg: 'bg-[#F4DEC2] hover:bg-white',
    headerBorder: 'border-slate-200/50',
    borderTop: 'border-t border-slate-200/50',
    TextHoverEffect: 'text-black px-3 py-2 rounded-lg transition hover:bg-gray-200',
    authHeading: 'text-xl sm:text-3xl font-bold text-center text-gray-900',
    authSubheading: 'text-base sm:text-lg font-normal text-center text-gray-600 mt-2',
    authMuted: 'text-xs text-gray-500 text-center',
  },

  app: {
    root: 'min-h-screen bg-gradient-to-br from-cyan-50 via-emerald-50 to-white text-slate-900 selection:bg-emerald-300/30 font-fraunces',
    appHeader: 'bg-white/50 backdrop-blur-md shadow-md font-semibold text-lg h-20 flex items-center',
    tabActive: 'font-semibold text-black',
    tabInactive: 'text-gray-600 hover:text-black transition-colors duration-200',
    dropdownIcon: 'w-5 h-5 cursor-pointer text-gray-700 hover:text-black transition-colors duration-200',
    dropdownMenu: 'absolute right-0 mt-2 w-36 bg-white/70 backdrop-blur-md border border-white/30 rounded-xl shadow-lg z-50 overflow-hidden',
    dropdownButton: 'w-full flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-white/20 transition-colors duration-150',
    dropdownIconButton: 'w-4 h-4 mr-2',
    avatarImage: 'w-8 h-8 rounded-full object-cover ring-2 ring-white',
    avatarFallback: 'w-8 h-8 rounded-full bg-gray-300 flex items-center justify-center text-white font-bold',
    submitButton: 'absolute bottom-4 right-4 px-3 py-1 text-xs bg-gradient-to-r \
    from-[#0284c7] via-[#0ea5e9] to-[#22d3ee] hover:from-[#0369a1] \
    hover:to-[#06b6d4] text-white font-medium shadow-lg \
    rounded-md transition-transform hover:-translate-y-0.5 disabled:opacity-50',
    card: 'bg-white/40 backdrop-blur-lg border border-white/30 rounded-xl shadow-lg px-6 py-4 transition-transform hover:-translate-y-1 hover:shadow-xl',
    cardHeadinglarge: 'text-3xl sm:text-4xl font-semibold text-slate-900 tracking-tight',
    cardHeadingSecondary: 'text-base sm:text-lg font-medium text-slate-800',
    cardSubheading: 'mt-2 text-sm text-gray-600',
    primarytext: 'text-sm text-slate-700',
    primaryButton: 'w-full max-w-[250px] px-4 py-2 bg-gradient-to-r from-[#0284c7] via-[#0ea5e9] to-[#22d3ee] hover:from-[#0369a1] hover:to-[#06b6d4] text-white font-medium rounded-xl disabled:opacity-50 mt-5 transition-transform hover:-translate-y-0.5 shadow-lg',
    inputfield: 'w-full bg-white/60 backdrop-blur-sm border border-gray-300 rounded px-3 py-2 mt-5 placeholder-gray-500 focus:outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-600',
    questionText: 'mt-2 text-sm text-gray-700 mb-1',
  },
  roadmap: {
    container: 'max-w-4xl mx-auto p-6',
    header: 'mb-8',
    titleContainer: 'flex items-center justify-between mb-4',
    title: 'text-3xl sm:text-4xl font-semibold text-slate-900 tracking-tight flex items-center',
    titleIcon: 'text-3xl mr-3',
    copyButton: 'px-4 py-2 bg-gradient-to-r from-[#0284c7] via-[#0ea5e9] to-[#22d3ee] hover:from-[#0369a1] hover:to-[#06b6d4] text-white font-medium rounded-xl transition-transform hover:-translate-y-0.5 shadow-lg flex items-center gap-2',
    statsText: 'text-sm text-slate-700',
    weekContainer: 'space-y-8',
    weekCard: 'bg-white/40 backdrop-blur-lg border border-white/30 rounded-xl shadow-lg p-6 transition-transform hover:-translate-y-1 hover:shadow-xl',
    weekHeader: 'text-2xl font-semibold text-slate-900 mb-6 flex items-center',
    weekBadge: 'bg-gradient-to-r from-[#0284c7] to-[#22d3ee] text-white rounded-full w-10 h-10 flex items-center justify-center text-sm font-bold mr-3 shadow-lg',
    topicContainer: 'space-y-6',
    topicCard: 'bg-white/60 backdrop-blur-sm border border-white/20 rounded-xl p-6 shadow-md hover:shadow-lg transition-all duration-200',
    topicHeader: 'flex items-start justify-between mb-4',
    topicTitle: 'text-xl font-semibold text-slate-900 mb-2',
    durationBadge: 'bg-emerald-100 text-emerald-700 px-3 py-1 rounded-full text-sm font-medium flex items-center gap-1',
    typeBadge: 'bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm font-medium flex items-center gap-1',
    sectionTitle: 'font-semibold text-slate-800 mb-3 flex items-center gap-2',
    description: 'text-slate-700 leading-relaxed mb-4',
    videoContainer: 'w-fit bg-white/80 backdrop-blur-sm border border-white/40 rounded-xl transition-all duration-200 cursor-pointer group',
    videoThumbnailContainer: 'relative overflow-hidden rounded-lg mb-3',
    videoThumbnail: 'h-48 w-auto object-cover transition-transform duration-200 group-hover:scale-105',
    videoPlayOverlay: 'absolute inset-0 bg-black/20 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-200',
    videoPlayButton: 'bg-red-600 text-white p-3 rounded-full shadow-lg transform scale-90 group-hover:scale-100 transition-transform duration-200',
    videoTitle: 'font-medium text-slate-800 text-sm leading-tight',
    resourceSection: 'space-y-3',
    resourceItem: 'bg-white/80 backdrop-blur-sm border border-white/40 rounded-lg p-3 hover:shadow-md transition-all duration-200 cursor-pointer group',
    resourceContent: 'flex items-center gap-3',
    resourceFavicon: 'w-5 h-5 rounded flex-shrink-0',
    resourceTitle: 'text-slate-700 text-sm font-medium group-hover:text-slate-900 transition-colors duration-150 flex-1 line-clamp-2',
    resourceLink: 'text-cyan-600 group-hover:text-cyan-700 transition-colors duration-150',
    footer: 'mt-8 text-center text-slate-600 text-sm bg-white/30 backdrop-blur-sm rounded-xl p-4 border border-white/30',
    footerText: 'flex items-center justify-center gap-2'
  }
};